# Generated by Django 4.2.11 on 2025-11-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tools_used',
        ),
    ]
